<!--
 * @Date: 2024-02-23 14:04:09
 * @LastEditors: zhangtiantian08 zhangtiantian08@58.com
 * @LastEditTime: 2024-03-27 19:29:50
 * @FilePath: /2023/js/index.html
-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <div id="overview">2121</div>
        <script>
            const promiseResolve = function (promise, x, resolve, reject) {
                if (promise === x) {
                    return reject(new Error("死循环"));
                }
                if (
                    (typeof x === "object" && x !== null) ||
                    typeof x === "function"
                ) {
                    try {
                        const then = x.then;
                        then.call(
                            x,
                            (y) => {
                                promiseResolve(promise, y, resolve, reject);
                            },
                            (r) => {
                                promiseResolve(promise, r, resolve, reject);
                            }
                        );
                    } catch (err) {
                        return reject(err);
                    }
                } else {
                    return resolve(x);
                }
            };
            const PENDING = "pending";
            const FULFILLED = "fulfilled";
            const REJECTED = "rejected";
            class MyPromise {
                constructor(executor) {
                    this.status = PENDING;
                    this.value = undefined;
                    this.reason = undefined;
                    this.fullFilledCallbacks = [];
                    this.rejectedCallbacks = [];
                    const resolve = (value) => {
                        if (this.status === PENDING) {
                            this.value = value;
                            this.status = FULFILLED;
                            this.fullFilledCallbacks.map((fn) =>
                                fn(this.value)
                            );
                        }
                    };
                    const reject = (reason) => {
                        if (this.status === PENDING) {
                            this.reason = reason;
                            this.status = REJECTED;
                            this.rejectedCallbacks.map((fn) => fn(this.reason));
                        }
                    };
                    try {
                        executor(resolve, reject);
                    } catch {}
                }
            }

            MyPromise.prototype.then = function (onFullFilled, onRejected) {
                onFullFilled = onFullFilled
                    ? onFullFilled
                    : () => {
                          this.value;
                      };
                onRejected = onRejected
                    ? onRejected
                    : () => {
                          this.reason;
                      };
                const promise2 = new MyPromise((resolve, reject) => {
                    if (this.status === FULFILLED) {
                        const x = onFullFilled(this.value);
                        console.log("x :>> ", x);
                        setTimeout(() => {
                            promiseResolve(promise2, x, resolve, reject);
                        }, 0);
                    } else if (this.status === REJECTED) {
                        const x = onRejected(this.reason);
                        setTimeout(() => {
                            promiseResolve(promise2, x, resolve, reject);
                        }, 0);
                    } else if (this.status === PENDING) {
                        this.fullFilledCallbacks.push(onFullFilled);
                        this.rejectedCallbacks.push(onRejected);
                    }
                });
                return promise2;
            };

            const promise = new Promise((resolve, reject) => {
                resolve(111);
            });
            const promise2 = promise.then((res) => {
                return new Promise((resolve, reject) => {
                    resolve(222);
                });
            });

            promise2
                .then((res) => {
                    console.log("res :>> ", res);
                    return 33;
                })
                .then((res) => {
                    console.log("res22 :>> ", res);
                });

            // const promise3 = Promise.resolve().then(() => {
            //     return promise3;
            // });
            // promise3
            //     .then((res) => {
            //         console.log("res :>> ", res);
            //     })
            //     .catch(console.error);
            // 执行结果如下：
            // TypeError: Chaining cycle detected for promise #<Promise>
            //    at <anonymous>
            //    at process._tickCallback (internal/process/next_tick.js:188:7)
            //    at Function.Module.runMain (module.js:667:11)
            //    at startup (bootstrap_node.js:187:16)
            //    at bootstrap_node.js:607:3
        </script>
    </body>
</html>
